import { NextResponse } from "next/server";

const appUrl = process.env.NEXT_PUBLIC_URL ?? "https://harvest-miniapp.example";

// Mini App manifest. `accountAssociation` must be generated by signing the
// deployed domain with the project's Farcaster custody key (via the
// Base / Farcaster manifest tool) before publishing - left blank here for
// the first iteration so the structure is in place.
export function GET() {
  return NextResponse.json({
    accountAssociation: {
      header: "",
      payload: "",
      signature: "",
    },
    miniapp: {
      version: "1",
      name: "Harvest",
      subtitle: "Base season",
      description:
        "Put your assets on autopilot. WETH, USDC and cbBTC autopilots on Base.",
      iconUrl: `${appUrl}/icon.png`,
      homeUrl: appUrl,
      splashImageUrl: `${appUrl}/splash.png`,
      splashBackgroundColor: "#ffb936",
      primaryCategory: "finance",
      tags: ["defi", "yield", "base", "autopilot"],
    },
  });
}
